### ISSUE TITLE
Ne publier sous forme de package PyPI qu'en cas de push sur master

### ISSUE THREAD

**Issue by fcoufour** [betagouv/indice_pollution#72]
Aujourd'hui `.github/workflows/build_publish.yml` est déclenché à chaque push quelques soit la branche via :
```
on: [push]
```

Il faudrait sans doute mettre ceci :
```
on:
    push:
        branches:
            - master
```
